spring.application.name=Warehouse Manager
spring.datasource.url=jdbc:postgresql://localhost:5432/wms_db
spring.datasource.username=binhjeremy
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=9090